#### Numpy

Numpy is a fundamental library for scientific computing in python. It provides support for arrays and martices, along with the collection of mathematical functions to operate on these data structures.

In [2]:
import numpy as np

In [3]:
## create array using numpy
## create 1D array

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5) # 1-row and 5-columns

array([[1, 2, 3, 4, 5]])

In [5]:
arr3 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(arr3.shape)

(3, 5)


In [6]:
## Creating arrays using methods

np.arange(0, 10, 2) # Create array from elements in range 0 to 10(10 excluded) with a step of 2

array([0, 2, 4, 6, 8])

In [7]:
np.arange(0, 10, 2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
## In-built functions present in numpy arrays

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# Identity Matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
print(arr3.ndim) # Number of dimensions

2


In [ ]:
print(arr3.size) # Number of elements

15


In [12]:
print(arr3.dtype) # Data-type

int64


In [13]:
print(arr3.itemsize) # Element size in bytes

8


#### Numpy Vectorised Operations

In [14]:
arr5 = np.array([1, 2, 3, 4, 5])
arr6 = np.array([6, 7, 8, 9, 10])

In [15]:
## Element wise addition
print("Addition:", arr5+arr6)

## Element wise subtraction
print("Subtraction:", arr6-arr5)

## Element wise multiplication
print("Mmultiplication:", arr5*arr6)

## Element wise divisiion
print("Division:", arr6/arr5)

Addition: [ 7  9 11 13 15]
Subtraction: [5 5 5 5 5]
Mmultiplication: [ 6 14 24 36 50]
Division: [6.         3.5        2.66666667 2.25       2.        ]


In [23]:
## Universal functions -> Functions that apply to thhe  entire array

# Square Root
print(np.sqrt(arr5))

# Exponential
print(np.exp(arr5))

# Sine
print(np.sin(arr5))

# Natural log
print(np.log(arr5))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [24]:
## Array Slicing and Indexing

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
print(arr[0][2])
print(arr[0,2])

3
3


In [28]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [30]:
## Modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
arr[1:] = 9
print(arr)

[[100   2   3   4]
 [  9   9   9   9]
 [  9   9   9   9]]


In [33]:
### Statictical concept: Normaliztion -> To have mean of 0 and standard deviation of 1

data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and  standard deviation
mean = np.mean(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Standard Deviation:", std_dev)

# Normalized data
normalized_data = (data-mean)/std_dev
print("Normalized data:", normalized_data)

Mean: 3.0
Standard Deviation: 1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [35]:
### Statistics: Mean, median, mode, standard deviation, variance

mean = np.mean(data)
print(mean)

median = np.median(data)
print(median)

std_dev = np.std(data)
print(std_dev)

variance = np.var(data)
print(variance)

3.0
3.0
1.4142135623730951
2.0


In [40]:
### Logical Operation

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(data>5)

data[(data>5) & (data<9)]

[False False False False False  True  True  True  True  True]


array([6, 7, 8])