#### Numpy

Numpy is a fundamental library for scientific computing in python. It provides support for arrays and martices, along with the collection of mathematical functions to operate on these data structures.

In [1]:
import numpy as np

In [5]:
## create array using numpy
## create 1D array

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5) # 1-row and 5-columns

array([[1, 2, 3, 4, 5]])

In [7]:
arr3 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(arr3.shape)

(3, 5)


In [ ]:
## Creating arrays using methods

np.arange(0, 10, 2) # Create array from elements in range 0 to 10(10 excluded) with a step of 2

array([0, 2, 4, 6, 8])

In [9]:
np.arange(0, 10, 2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
## In-built functions present in numpy arrays